# Generated by Django 5.2.17 on 2026-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('gazebo', 'Беседка'), ('aviary', 'Вольер'), ('utility', 'Хозблок')], max_length=20, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='product_type',
            field=models.CharField(choices=[('gazebo', 'Беседка'), ('aviary', 'Вольер'), ('utility', 'Хозблок')], max_length=20, verbose_name='Тип товара'),
        ),
    ]
